version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/django_web
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/remove_server
      timeout: 300
      runas: ec2-user
  Install:
    - location: scripts/install_app
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server
      runas: ec2-user