version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/django_web
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/remove_server.sh
      timeout: 300
  Install:
    - location: scripts/install_app.sh
  ApplicationStart:
    - location: scripts/start_server.sh