version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/django_web
    overwrite: yes

hooks:
  ApplicationStop:
    - location: scripts/remove_server.sh
      timeout: 300
      runas: ec2-user
  Install:
    - location: scripts/install_app.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ec2-user