version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/django_web
    overwrite: yes

hooks:
  ApplicationStop:
    - location: scripts/remove_server.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh