version: '3'
services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf/traefik.toml:/etc/traefik/traefik.toml:ro"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django-api.rule=Host(`seonghun.com`)"
      - "traefik.http.routers.django-api.entrypoints=web"
    volumes:
      - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./static:/static"

  django-api:
    build:
      context: .
      dockerfile:  docker/Dockerfile
    image: 'django-api'
    container_name: django-api
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - reverse-proxy
      - postgres
      - nginx

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped