version: '3'
services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf/traefik.toml:/etc/traefik/traefik.toml:ro"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django-api.rule=Host(`seonghun.com`)"
      - "traefik.http.routers.django-api.entrypoints=web"
    volumes:
      - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./static:/static"

  django-api:
    image: 'django-api'
    build:
      context: .
      dockerfile:  docker/Dockerfile
    container_name: django-api
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - reverse-proxy
      - postgres
      - nginx

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=1q2w3e4r
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery-worker:
      image: celery-worker
      build:
        context: .
        dockerfile: docker/Dockerfile
      container_name: celery-worker
      command: celery -A config worker --loglevel=INFO
      depends_on:
        - reverse-proxy
        - django-api
      restart: always


#  celery-beat-worker:
#      image: django-api
#      container_name: celery-beat-worker
#      env_file:
#        - .env
#      command: celery -A worker worker --loglevel=INFO --concurrency=1 -Q beat
#      depends_on:
#        - django-api
#        - celery-common-worker
#      restart: always
#
#
#  celery-beat:
#      image: django-api
#      container_name: celery-beat
#      env_file:
#        - .env
#      command: celery -A worker beat -s ./task/schedule_beat_log/beat_log
#      depends_on:
#        - django-api
#        - celery-common-worker
#      restart: always


  flower:
    image: mher/flower
    ports:
      - "5555:5555"