name: Django CI Test

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.4]

    steps:
    - uses: actions/checkout@v4
    - name: Set up PostgreSQL
      uses: minesunny/postgresql-action@v1.0.0
      with:
        postgresql version: '14'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: .env settings
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY}}" >> .env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER}}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB}}" >> .env
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST}}" >> .env
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT}}" >> .env
        echo "CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL}}" >> .env
    - name: Run Tests
      run: |
        pytest
